### Import Libraries and Load Dataset

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('messy_customer_sales_data.csv')
data.head()

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
0,CUST4371,Paul Wilson,m,52.0,KOLKATA,2025-06-26,2025-05-17,26944.0,1.0,peckvictoria@example.com,2131107701,India
1,CUST5957,Jason Thomas,M,51.0 years,NaN,2021-02-17,2025-07-22,44152.0,2.0,owensanthony@example.com,1080761560,india
2,CUST3754,Brittney Martinez,F,62.0,hyderabad,2023-11-05,2024-12-08,31745.0,2.0,tara39@example.org,8981006345,India
3,CUST2934,Brenda Pierce,FEMALE,40.0,hyderabad,2022-03-13,2025-10-02,39674.0,1.0,berrynancy@example.org,8228064204,india
4,CUST5683,Matthew Carroll,f,41.0,CHENNAI,2024-04-05,2024-12-15,NaN,8.0,denise84@example.org,2665569480,India

In [3]:
data.shape

(10200, 12)

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10200 entries, 0 to 10199
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         9177 non-null   object
 1   Name                10200 non-null  object
 2   Gender              9174 non-null   object
 3   Age                 9249 non-null   object
 4   City                9184 non-null   object
 5   Signup_Date         10200 non-null  object
 6   Last_Purchase_Date  9188 non-null   object
 7   Purchase_Amount     9179 non-null   float64
 8   Feedback_Score      9177 non-null   float64
 9   Email               10200 non-null  object
 10  Phone_Number        10200 non-null  int64
 11  Country             9468 non-null   object
dtypes: float64(2), int64(1), object(9)
memory usage: 956.4+ KB

In [5]:
data.describe().round()

       Purchase_Amount  Feedback_Score  Phone_Number
count           9179.0          9177.0  1.020000e+04
mean           29090.0             5.0  4.979974e+09
std           208697.0             3.0  2.902593e+09
min             -500.0             1.0  9.208990e+05
25%            12295.0             3.0  2.449157e+09
50%            24330.0             5.0  4.988639e+09
75%            37130.0             8.0  7.510448e+09
max          9999999.0            10.0  9.994402e+09

### Check Missing Values

In [6]:
data.isnull().sum()

Customer_ID           1023
Name                     0
Gender                1026
Age                    951
City                  1016
Signup_Date              0
Last_Purchase_Date    1012
Purchase_Amount       1021
Feedback_Score        1023
Email                    0
Phone_Number             0
Country                732
dtype: int64

#### Remove Duplicate Records

In [7]:
data.duplicated().sum()

np.int64(15)

In [8]:
data = data.drop_duplicates()

In [9]:
data.shape

(10185, 12)

In [10]:
data.head()

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
0,CUST4371,Paul Wilson,m,52.0,KOLKATA,2025-06-26,2025-05-17,26944.0,1.0,peckvictoria@example.com,2131107701,India
1,CUST5957,Jason Thomas,M,51.0 years,NaN,2021-02-17,2025-07-22,44152.0,2.0,owensanthony@example.com,1080761560,india
2,CUST3754,Brittney Martinez,F,62.0,hyderabad,2023-11-05,2024-12-08,31745.0,2.0,tara39@example.org,8981006345,India
3,CUST2934,Brenda Pierce,FEMALE,40.0,hyderabad,2022-03-13,2025-10-02,39674.0,1.0,berrynancy@example.org,8228064204,india
4,CUST5683,Matthew Carroll,f,41.0,CHENNAI,2024-04-05,2024-12-15,NaN,8.0,denise84@example.org,2665569480,India

#### Clean Customer ID

In [11]:
data['Customer_ID'].isnull().sum()

np.int64(1022)

In [12]:
# fill missing values
data['Customer_ID'] = data['Customer_ID'].fillna('Unknown')

#### Clean Gender Column

In [13]:
print(data['Gender'].unique())

['m ' 'M' 'F' 'FEMALE' 'f ' 'male' 'MALE' 'female' nan]

In [14]:
data['Gender'] = data['Gender'].str.strip().str.upper()   #convert into uppercase

In [15]:
print(data['Gender'].head(5))

0         M
1         M
2         F
3    FEMALE
4         F
Name: Gender, dtype: object

In [16]:
# replace values
data['Gender'] = data['Gender'].replace({
    'M':'Male',
    'F':'Female',
    'MALE':'Male',
    'FEMALE':'Female'
})

In [ ]:
data['Gender'].fillna(data['Gender'].mode()[0], inplace=True)

In [18]:
data.isnull().sum()

Customer_ID              0
Name                     0
Gender                   0
Age                    950
City                  1014
Signup_Date              0
Last_Purchase_Date    1012
Purchase_Amount       1020
Feedback_Score        1022
Email                    0
Phone_Number             0
Country                731
dtype: int64

#### Clean Age Column

In [19]:
data['Age'].head(5)

0          52.0
1    51.0 years
2          62.0
3          40.0
4          41.0
Name: Age, dtype: object

In [20]:
data['Age'] = data['Age'].astype(str)
data['Age'] = data['Age'].str.extract('(\d+)')

In [21]:
data['Age'] = pd.to_numeric(data['Age'])

In [22]:
# fill missing ages
data['Age'] = data['Age'].fillna(data['Age'].median())

#### Clean City Column

In [23]:
data['City'].unique()

array([' KOLKATA ', nan, ' hyderabad ', ' CHENNAI ', ' kolkata ',
       ' BANGALORE ', ' Hyderabad ', ' HYDERABAD ', ' Mumbai ',
       ' chennai ', ' Delhi ', ' bangalore ', ' MUMBAI ', ' Bangalore ',
       ' Kolkata ', ' delhi ', ' Chennai ', ' mumbai ', ' DELHI '],
      dtype=object)

In [24]:
data['City'] = data['City'].str.strip().str.title()  # strip removes extra space

In [25]:
data['City'] = data['City'].fillna(data['City'].mode()[0])

#### Clean Country Column

In [26]:
data['Country'].unique()

array(['India', 'india', nan, 'InDia', 'IND'], dtype=object)

In [27]:
data['Country'] = data['Country'].str.strip().str.upper()

In [28]:
data['Country'] = data['Country'].replace({
    'IND':'India'
})

In [29]:
data['Country'] = data['Country'].fillna('India')

#### Convert Date Columns

In [30]:
data['Signup_Date'] = pd.to_datetime(data['Signup_Date'])

In [31]:
data['Last_Purchase_Date'] = pd.to_datetime(
    data['Last_Purchase_Date'])

In [32]:
data['Last_Purchase_Date'] = data['Last_Purchase_Date'].fillna(
    data['Last_Purchase_Date'].median()
)

#### Clean Purchase Amount

In [33]:
data['Purchase_Amount'].isnull().sum()

np.int64(1020)

In [34]:
data['Purchase_Amount'] = data['Purchase_Amount'].fillna(
    data['Purchase_Amount'].median()
)

In [35]:
data['Purchase_Amount'].isnull().sum()

np.int64(0)

#### Clean Feedback Score

In [36]:
data['Feedback_Score'] = data['Feedback_Score'].fillna(
    data['Feedback_Score'].median()
)

In [37]:
data['Feedback_Score'].isnull().sum()

np.int64(0)

In [38]:
data['Feedback_Score'] = data['Feedback_Score'].astype(int)

### Verify Cleaned Data

In [39]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
Index: 10185 entries, 0 to 10199
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         10185 non-null  object
 1   Name                10185 non-null  object
 2   Gender              10185 non-null  object
 3   Age                 10185 non-null  float64
 4   City                10185 non-null  object
 5   Signup_Date         10185 non-null  datetime64[ns]
 6   Last_Purchase_Date  10185 non-null  datetime64[ns]
 7   Purchase_Amount     10185 non-null  float64
 8   Feedback_Score      10185 non-null  int64
 9   Email               10185 non-null  object
 10  Phone_Number        10185 non-null  int64
 11  Country             10185 non-null  object
dtypes: datetime64[ns](2), float64(2), int64(2), object(6)
memory usage: 1.0+ MB
None

In [40]:
print(data.isnull().sum())

Customer_ID           0
Name                  0
Gender                0
Age                   0
City                  0
Signup_Date           0
Last_Purchase_Date    0
Purchase_Amount       0
Feedback_Score        0
Email                 0
Phone_Number          0
Country               0
dtype: int64

In [41]:
print(data.head())

  Customer_ID               Name  Gender   Age       City Signup_Date  \
0    CUST4371        Paul Wilson    Male  52.0    Kolkata  2025-06-26
1    CUST5957       Jason Thomas    Male  51.0     Mumbai  2021-02-17
2    CUST3754  Brittney Martinez  Female  62.0  Hyderabad  2023-11-05
3    CUST2934      Brenda Pierce  Female  40.0  Hyderabad  2022-03-13
4    CUST5683    Matthew Carroll  Female  41.0    Chennai  2024-04-05

  Last_Purchase_Date  Purchase_Amount  Feedback_Score  \
0         2025-05-17          26944.0               1
1         2025-07-22          44152.0               2
2         2024-12-08          31745.0               2
3         2025-10-02          39674.0               1
4         2024-12-15          24330.0               8

                      Email  Phone_Number Country
0  peckvictoria@example.com    2131107701   INDIA
1  owensanthony@example.com    1080761560   INDIA
2        tara39@example.org    8981006345   INDIA
3    berrynancy@example.org    8228064204   INDIA
4      denise84@example.org    2665569480   INDIA

#### Save Cleaned Dataset

In [44]:
data.to_csv("cleaned_customer_sales_data.csv", index=False)

print("Dataset Saved Successfully")

Dataset Saved Successfully

In [45]:
import os
print(os.getcwd())

C:\Users\ANIKET\Data Analytics Jupyter\Practice Folder